### ISSUE TITLE
Installation guide missing initial npm installation

### ISSUE THREAD

**Issue by deckar01** [servant-app/JAWS#10]
**Current behavior:**
The installation guide starts with configuration and does not walk the dev through npm installation.

The installation step *"open the temp.env file located in the lib folder"* assumes the module is installed in the application, but does not list it as a prerequisite step.

**Expected behavior:**
The installation guide should start with running the command ```npm install --save jaws-stack``` in their project.

**Notes:**
Trivial, but a potential stumbling block.

**Comment by deckar01** [comment]
It also wouldn't hurt to include it in the readme.

**Comment by ac360** [comment]
Thanks.  I'll fix this right away!

**Comment by ac360** [comment]
Done.

**Comment by deckar01** [comment]
I'm not exactly sure what you changed, but the wiki doesn't seem to have the info I was suggesting.

Using pull requests and referencing their issues helps keep things organized (although the wiki doesn't exactly have PRs).

Issue #5 was closed without reference to the commit you made to fix it and will be lost in the sands of time.

**Comment by kraigh** [comment]
I also don't see this reflected in the wiki, and it took me a minute to poke around to find the npm module name.

**Comment by kraigh** [comment]
Side note: is there a good way to suggest wiki updates?

**Comment by callmeStriking** [comment]
The edit button? If your revision is wrong, it can be undone. It doesn't need project leader approval, just like they do it on Wikipedia!
