### ISSUE TITLE
requires node 0.12.x?

### ISSUE THREAD

**Issue by doapp-ryanp** [servant-app/JAWS#17]
Great start here man.

Curious - why do all your `package.json` files require node 0.12 when lambda only supports 0.10.33?

FWIW we've [been trying to get an official response from AWS](https://forums.aws.amazon.com/thread.jspa?messageID=663973&#663973) on how they are going to support versions because the current way of packaging your own doesn't appeal to us.

**Comment by ac360** [comment]
Nice find!  I'll fix this later today.

**Comment by doapp-ryanp** [comment]
I'll fix it, I have a decent size pull request coming your way in the next day or so with some new enhancements.  I'll just include the fix in it.

**Comment by ac360** [comment]
Thanks, I can't wait to see it!

**Comment by ac360** [comment]
Ryan, 

I had to do some breaking changes in v0.0.3, which included lots of package.json modifications and I decided to change the node version at that time. 

I still look forward to your pull request.  You seem close to the node version/lambda issue and I value your input on this project. 

Thanks, 
Austen

**Comment by ac360** [comment]
Fixed in becb4fa
