### ISSUE TITLE
Why site isn't simply static?

### ISSUE THREAD

**Issue by remicastaing** [servant-app/JAWS#32]
I'm wondering why `/site` are not containing a simple single page app but a node+express app.

If you want to deploy the client part on AWS S3, it needs to be fully static.

**Comment by ac360** [comment]
@remicastaing The node/express part of `site` is so that you can develop your JAWS website locally.  The node/express component is not meant to be uploaded.  It's only for developer convenience (one of my big themes).

**Comment by ac360** [comment]
@remicastaing BTW - the `site` module is one of the more under-developed parts of JAWS.  It is intended to be fully static and the JAWS CLI will soon have commands to minify, zip and upload all assets to S3/Cloudfront/elsewhere :)

**Comment by remicastaing** [comment]
Thanks, @ac360. Do you have a framework to handle the client side in mind?

**Comment by austinrivas** [comment]
I personally think jaws should be client agnostic, provide some example
integrations with react / angular

**Comment by ac360** [comment]
@remicastaing  I prefer to make JAWS client agnostic like @austinrivas suggested.  I've just put JAWS into its own Github organization so that we can make more repos for the different front-end frameworks.

**Comment by remicastaing** [comment]
You're both right. If one framework can do it, then another can do it as well.
