### ISSUE TITLE
Running `signin` lambda example fails

### ISSUE THREAD

**Issue by koddsson** [servant-app/JAWS#6]
It because the variables `JWT_ISSUER` and `JWT_SECRET` are not set but they weren't mentioned in the [installation guide](https://github.com/servant-app/JAWS/wiki/JAWS-Installation).

**Comment by koddsson** [comment]
I didn't know I could but I just edited the wiki to mention adding a JWT_SECRET variable at the bottom.

**Comment by ac360** [comment]
I'll fix this right now!

**Comment by ac360** [comment]
Thanks for the help :)
